// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: master/pb/task.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecuteTask_GetExecutionRequest_FullMethodName = "/pb.ExecuteTask/GetExecutionRequest"
	ExecuteTask_UpdateTaskStatus_FullMethodName    = "/pb.ExecuteTask/UpdateTaskStatus"
	ExecuteTask_UpdateTaskResult_FullMethodName    = "/pb.ExecuteTask/UpdateTaskResult"
)

// ExecuteTaskClient is the client API for ExecuteTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecuteTaskClient interface {
	GetExecutionRequest(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	UpdateTaskStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	UpdateTaskResult(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type executeTaskClient struct {
	cc grpc.ClientConnInterface
}

func NewExecuteTaskClient(cc grpc.ClientConnInterface) ExecuteTaskClient {
	return &executeTaskClient{cc}
}

func (c *executeTaskClient) GetExecutionRequest(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, ExecuteTask_GetExecutionRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeTaskClient) UpdateTaskStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, ExecuteTask_UpdateTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeTaskClient) UpdateTaskResult(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, ExecuteTask_UpdateTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecuteTaskServer is the server API for ExecuteTask service.
// All implementations must embed UnimplementedExecuteTaskServer
// for forward compatibility.
type ExecuteTaskServer interface {
	GetExecutionRequest(context.Context, *ExecutionRequest) (*ExecutionResponse, error)
	UpdateTaskStatus(context.Context, *UpdateRequest) (*UpdateResponse, error)
	UpdateTaskResult(context.Context, *UpdateRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedExecuteTaskServer()
}

// UnimplementedExecuteTaskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecuteTaskServer struct{}

func (UnimplementedExecuteTaskServer) GetExecutionRequest(context.Context, *ExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionRequest not implemented")
}
func (UnimplementedExecuteTaskServer) UpdateTaskStatus(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}
func (UnimplementedExecuteTaskServer) UpdateTaskResult(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskResult not implemented")
}
func (UnimplementedExecuteTaskServer) mustEmbedUnimplementedExecuteTaskServer() {}
func (UnimplementedExecuteTaskServer) testEmbeddedByValue()                     {}

// UnsafeExecuteTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecuteTaskServer will
// result in compilation errors.
type UnsafeExecuteTaskServer interface {
	mustEmbedUnimplementedExecuteTaskServer()
}

func RegisterExecuteTaskServer(s grpc.ServiceRegistrar, srv ExecuteTaskServer) {
	// If the following call pancis, it indicates UnimplementedExecuteTaskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecuteTask_ServiceDesc, srv)
}

func _ExecuteTask_GetExecutionRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteTaskServer).GetExecutionRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteTask_GetExecutionRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteTaskServer).GetExecutionRequest(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteTask_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteTaskServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteTask_UpdateTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteTaskServer).UpdateTaskStatus(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteTask_UpdateTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteTaskServer).UpdateTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteTask_UpdateTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteTaskServer).UpdateTaskResult(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecuteTask_ServiceDesc is the grpc.ServiceDesc for ExecuteTask service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecuteTask_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ExecuteTask",
	HandlerType: (*ExecuteTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExecutionRequest",
			Handler:    _ExecuteTask_GetExecutionRequest_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _ExecuteTask_UpdateTaskStatus_Handler,
		},
		{
			MethodName: "UpdateTaskResult",
			Handler:    _ExecuteTask_UpdateTaskResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master/pb/task.proto",
}
