// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: master/pb/task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_master_pb_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_pb_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_master_pb_task_proto_rawDescGZIP(), []int{0}
}

type ExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=Language,proto3" json:"Language,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_master_pb_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_pb_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_master_pb_task_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutionResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecutionResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_master_pb_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_pb_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_master_pb_task_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_master_pb_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_pb_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_master_pb_task_proto_rawDescGZIP(), []int{3}
}

var File_master_pb_task_proto protoreflect.FileDescriptor

const file_master_pb_task_proto_rawDesc = "" +
	"\n" +
	"\x14master/pb/task.proto\x12\x02pb\"\x12\n" +
	"\x10ExecutionRequest\"\x83\x01\n" +
	"\x11ExecutionResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x1a\n" +
	"\bLanguage\x18\x03 \x01(\tR\bLanguage\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x12\x16\n" +
	"\x06Result\x18\x05 \x01(\tR\x06Result\"7\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\"\x10\n" +
	"\x0eUpdateResponse2\xcd\x01\n" +
	"\vExecuteTask\x12D\n" +
	"\x13GetExecutionRequest\x12\x14.pb.ExecutionRequest\x1a\x15.pb.ExecutionResponse\"\x00\x12;\n" +
	"\x10UpdateTaskStatus\x12\x11.pb.UpdateRequest\x1a\x12.pb.UpdateResponse\"\x00\x12;\n" +
	"\x10UpdateTaskResult\x12\x11.pb.UpdateRequest\x1a\x12.pb.UpdateResponse\"\x00B(Z&github.com/kash2104/taskflow/master/pbb\x06proto3"

var (
	file_master_pb_task_proto_rawDescOnce sync.Once
	file_master_pb_task_proto_rawDescData []byte
)

func file_master_pb_task_proto_rawDescGZIP() []byte {
	file_master_pb_task_proto_rawDescOnce.Do(func() {
		file_master_pb_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_pb_task_proto_rawDesc), len(file_master_pb_task_proto_rawDesc)))
	})
	return file_master_pb_task_proto_rawDescData
}

var file_master_pb_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_master_pb_task_proto_goTypes = []any{
	(*ExecutionRequest)(nil),  // 0: pb.ExecutionRequest
	(*ExecutionResponse)(nil), // 1: pb.ExecutionResponse
	(*UpdateRequest)(nil),     // 2: pb.UpdateRequest
	(*UpdateResponse)(nil),    // 3: pb.UpdateResponse
}
var file_master_pb_task_proto_depIdxs = []int32{
	0, // 0: pb.ExecuteTask.GetExecutionRequest:input_type -> pb.ExecutionRequest
	2, // 1: pb.ExecuteTask.UpdateTaskStatus:input_type -> pb.UpdateRequest
	2, // 2: pb.ExecuteTask.UpdateTaskResult:input_type -> pb.UpdateRequest
	1, // 3: pb.ExecuteTask.GetExecutionRequest:output_type -> pb.ExecutionResponse
	3, // 4: pb.ExecuteTask.UpdateTaskStatus:output_type -> pb.UpdateResponse
	3, // 5: pb.ExecuteTask.UpdateTaskResult:output_type -> pb.UpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_master_pb_task_proto_init() }
func file_master_pb_task_proto_init() {
	if File_master_pb_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_pb_task_proto_rawDesc), len(file_master_pb_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_pb_task_proto_goTypes,
		DependencyIndexes: file_master_pb_task_proto_depIdxs,
		MessageInfos:      file_master_pb_task_proto_msgTypes,
	}.Build()
	File_master_pb_task_proto = out.File
	file_master_pb_task_proto_goTypes = nil
	file_master_pb_task_proto_depIdxs = nil
}
